# Generated by Django 2.2.6 on 2019-10-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_onenote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneNote',
        ),
    ]
