# Generated by Django 2.2.6 on 2019-10-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20191022_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='body',
        ),
    ]
