# Generated by Django 2.2.7 on 2019-11-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
